### ISSUE TITLE
gem serve all version rails 4?

### ISSUE THREAD

**Issue by dieuit07** [PugglePay/validates-structure#2]
In wiki "The gem works for ActiveModel 4 and above."
But I see in gem lock, it locked by <= 4.1.1 
So I am using rails 4.2.1 could not install.

**Comment by Jell** [comment]
Hum... I don't know if 4.2 would have breaking changes to active model. But if you feel like trying out and committing a patch, please do!

**Comment by dieuit07** [comment]
I am not sure. But when I clone source to local and edit gemspec, it work fine
