### ISSUE TITLE
duplicate errors message

### ISSUE THREAD

**Issue by dieuit07** [PugglePay/validates-structure#4]
It print out error off 2 languages but meaning the same. is there any config I missing?

["/contact/title không thể để trắng", "/contact/title must not be empty"]

**Comment by Jell** [comment]
Hum I think if you use the the built-in validators, we don't do any localisation (that's an oversight).

You could either skip the built-in validations or patch the code here to add localisation:

```
https://github.com/PugglePay/validates-structure/blob/master/lib/validates-structure.rb#L156
```

Cheers!

**Comment by dieuit07** [comment]
Yeap ;)
